#!/usr/bin/env ys-0

use ys::taptest: :all

test::

- name: generated-comment-is-not-imported
  cmnd: bin/ysd -f jsc -t ysd -
  stdi: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "$comment":
        "DO NOT EDIT. THIS FILE GENERATED BY YAMLSCHEMA v0.1.0",
      "type": "object",
      "additionalProperties": false
    }
  want: |
    # Converted from JSON Schema
    {}

- name: generated-comment-does-not-roundtrip
  cmnd: bin/ysd -R -f jsc -
  stdi: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "$comment":
        "DO NOT EDIT. THIS FILE GENERATED BY YAMLSCHEMA v0.1.0",
      "type": "object",
      "additionalProperties": false
    }
  want: |
    OK

- name: explicit-true-additional-properties-roundtrip
  cmnd: bin/ysd -R -f jsc -
  stdi: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "config": {
          "type": "object",
          "additionalProperties": true
        }
      },
      "additionalProperties": true
    }
  want: |
    OK

- name: singleton-ref-allof-with-properties-roundtrip
  cmnd: bin/ysd -R -f jsc -
  stdi: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "$defs": {
        "base": {
          "type": "object",
          "properties": {"shared": {"type": "string"}}
        }
      },
      "type": "object",
      "properties": {
        "component": {
          "type": "object",
          "description": "Component",
          "allOf": [{"$ref": "#/$defs/base"}],
          "properties": {"local": {"type": "integer"}}
        }
      },
      "additionalProperties": false
    }
  want: |
    OK

- name: required-only-combinator-branches-roundtrip
  cmnd: bin/ysd -R -f jsc -
  stdi: |
    {
      "type": "object",
      "properties": {
        "choice": {
          "oneOf": [
            {"required": ["Action"]},
            {"required": ["NotAction"]}
          ]
        }
      },
      "additionalProperties": false
    }
  want: |
    OK

- name: object-property-combinators-roundtrip
  cmnd: bin/ysd -R -f jsc -
  stdi: |
    {
      "type": "object",
      "properties": {
        "single": {
          "type": "object",
          "properties": {
            "package_pip": {"type": "string"}
          },
          "oneOf": [
            {"required": ["package_pip"]}
          ],
          "additionalProperties": false
        },
        "multi": {
          "type": "object",
          "properties": {
            "a": {"type": "string"},
            "b": {"type": "integer"}
          },
          "oneOf": [
            {"required": ["a"]},
            {"required": ["b"]}
          ],
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  want: |
    OK

- name: required-property-order-does-not-affect-roundtrip
  cmnd: bin/ysd -R -f jsc -
  stdi: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "aliases": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "ip": {"type": "string"},
              "hostnames": {
                "type": "array",
                "items": {"type": "string"}
              }
            },
            "required": ["ip", "hostnames"]
          }
        }
      },
      "additionalProperties": false
    }
  want: |
    OK

- name: scalar-or-list-array-first-roundtrip
  cmnd: bin/ysd -R -f jsc -
  stdi: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "ids": {
          "anyOf": [
            {
              "type": "array",
              "items": {"type": "integer"},
              "minItems": 1,
              "uniqueItems": true
            },
            {"type": "integer"}
          ]
        }
      },
      "additionalProperties": false
    }
  want: |
    OK

- name: explicit-any-solo-list-roundtrip
  cmnd: bin/ysd -R -f ysd -
  stdi: |
    value:
      .any:
      - .type: +Str
        .match: x
      - .type: +Str[]
        .match: x
        .size: [1]
  want: |
    OK

- name: metadata-roundtrip
  cmnd: |
    sh -c '
      set -eu
      d=$(mktemp -d)
      cat > "$d/in.schema.json"
      bin/ysd -t ysd.yaml "$d/in.schema.json" > "$d/out.ysd.yaml"
      bin/ysd -t schema.json "$d/out.ysd.yaml" > "$d/out.schema.json"
      ys -pe "ARGS.0:read:json/load == select-keys( \
        ARGS.1:read:json/load ARGS.0:read:json/load:keys)" \
        -- "$d/in.schema.json" "$d/out.schema.json"
    '
  stdi: |
    {
      "$id": "https://example.com/arrays.schema.json",
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "title": "Arrays",
      "description": "Arrays of strings and objects",
      "type": "object",
      "properties": {
        "fruits": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "vegetables": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/veggie"
          }
        }
      },
      "$defs": {
        "veggie": {
          "type": "object",
          "description": "A vegetable record.",
          "required": ["veggieName", "veggieLike"],
          "properties": {
            "veggieName": {
              "type": "string",
              "title": "Vegetable name",
              "description": "The name of the vegetable."
            },
            "veggieLike": {
              "type": "boolean",
              "description": "Do I like this vegetable?"
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  want: |
    true

- name: constraints-roundtrip
  cmnd: |
    sh -c '
      set -eu
      d=$(mktemp -d)
      cat > "$d/in.schema.json"
      bin/ysd -t ysd.yaml "$d/in.schema.json" > "$d/out.ysd.yaml"
      bin/ysd -t schema.json "$d/out.ysd.yaml" > "$d/out.schema.json"
      ys -pe "ARGS.0:read:json/load == select-keys( \
        ARGS.1:read:json/load ARGS.0:read:json/load:keys)" \
        -- "$d/in.schema.json" "$d/out.schema.json"
    '
  stdi: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "role": {"type": "string", "enum": ["admin", "user", "guest"]},
        "version": {"const": "v1"},
        "host": {"type": "string", "default": "localhost"},
        "port": {"type": "integer", "minimum": 1, "maximum": 65535},
        "tags": {
          "type": "array",
          "items": {"type": "string"},
          "uniqueItems": true,
          "minItems": 1,
          "maxItems": 3
        },
        "anything": {"type": "array"},
        "routeOverrides": {
          "type": "object",
          "description": "Per-group overrides."
        }
      },
      "required": [
        "role", "version", "host", "port", "tags", "anything",
        "routeOverrides"
      ],
      "additionalProperties": false
    }
  want: |
    true

done:
