#!/usr/bin/env ys-0

use ys::taptest: :all

test::

- name: generated-comment
  cmnd: |
    sh -c '
      set -eu
      tmp=$(mktemp -d)
      trap "rm -r \"$tmp\"" EXIT
      printf "name: +Str\n" > "$tmp/contact.ysd.yaml"
      bin/ysd -t jsc -C "$tmp/contact.ysd.yaml" |
        perl -pe "s/YAMLSCHEMA v[0-9]+[.][0-9]+[.][0-9]+/YAMLSCHEMA vVERSION/"
    '
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","$comment":"DO NOT EDIT. THIS FILE GENERATED BY YAMLSCHEMA vVERSION","type":"object","additionalProperties":false,"required":["name"],"properties":{"name":{"type":"string"}}}

- name: types-to-schema.json
  cmnd: bin/ysd -t jsc -C -
  stdi: |
    s: +Str
    i: +Int
    n: +Num
    b: +Bool
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","additionalProperties":false,"required":["s","i","n","b"],"properties":{"s":{"type":"string"},"i":{"type":"integer"},"n":{"type":"number"},"b":{"type":"boolean"}}}

- name: refs-and-regex-to-schema.json
  cmnd: bin/ysd -t jsc -C -
  stdi: |
    +email: +Str ~"\S+@\S+"

    host: +Str
    admin?: +email
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","additionalProperties":false,"required":["host"],"$defs":{"email":{"type":"string","pattern":"^\\S+@\\S+$"}},"properties":{"host":{"type":"string"},"admin":{"$ref":"#\/$defs\/email"}}}

- name: match-find-and-regex-to-schema.json
  cmnd: bin/ysd -t jsc -C -
  stdi: |
    full: ~"{plus}{digit}+"
    alias: match:"xyz"
    found: ~~"{upper}{lower}+"
    short: find:"abc"
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","additionalProperties":false,"required":["full","alias","found","short"],"properties":{"full":{"type":"string","pattern":"^\\+[0-9]+$"},"alias":{"type":"string","pattern":"^xyz$"},"found":{"type":"string","pattern":"[A-Z][a-z]+"},"short":{"type":"string","pattern":"abc"}}}

- name: defs-only-to-schema.json
  cmnd: bin/ysd -t jsc -C -
  stdi: |
    +airflow: +Str [front-to-rear,rear-to-front]
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","$defs":{"airflow":{"type":"string","enum":["front-to-rear","rear-to-front"]}}}

- name: defs-only-roundtrip
  cmnd: sh -c 'bin/ysd -Rq - && echo OK'
  stdi: |
    {
      "$defs": {
        "airflow": {
          "type": "string",
          "enum": ["front-to-rear", "rear-to-front"]
        }
      }
    }
  want: |
    OK

- name: compact-enum-to-schema.json
  cmnd: bin/ysd -t jsc -C -
  stdi: |
    role: +Str [admin,user,guest]
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","additionalProperties":false,"required":["role"],"properties":{"role":{"type":"string","enum":["admin","user","guest"]}}}

- name: list-suffix-to-schema.json
  cmnd: bin/ysd -t jsc -C -
  stdi: |
    tags: +Str[1+,!]
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","additionalProperties":false,"required":["tags"],"properties":{"tags":{"type":"array","minItems":1,"uniqueItems":true,"items":{"type":"string"}}}}

- name: any-list-omits-empty-items
  cmnd: bin/ysd -t jsc -C -
  stdi: |
    anything: +Any[]
    strings: +Str[]
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","additionalProperties":false,"required":["anything","strings"],"properties":{"anything":{"type":"array"},"strings":{"type":"array","items":{"type":"string"}}}}

- name: explicit-block-to-schema.json
  cmnd: bin/ysd -t jsc -C -
  stdi: |
    port:
      .type: +Int
      .range: 1..65535
      .init: 8080
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","additionalProperties":false,"required":["port"],"properties":{"port":{"type":"integer","default":8080,"minimum":1,"maximum":65535}}}

- name: numeric-range-shorthand-to-schema.json
  cmnd: bin/ysd -t jsc -C -
  stdi: |
    port: 1..65535
    age: 0..
    debt: ..-1
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","additionalProperties":false,"required":["port","age","debt"],"properties":{"port":{"type":"integer","minimum":1,"maximum":65535},"age":{"type":"integer","minimum":0},"debt":{"type":"integer","maximum":-1}}}

- name: annotations-to-schema.json
  cmnd: bin/ysd -t jsc -C -
  stdi: |
    --: Arrays
    -: Arrays of strings and objects
    .id: https://example.com/arrays.ysd.yaml
    name:
      --: Full name
      -: Display name.
      .type: +Str
  want: |
    {"$id":"https:\/\/example.com\/arrays.schema.json","$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","title":"Arrays","description":"Arrays of strings and objects","type":"object","additionalProperties":false,"required":["name"],"properties":{"name":{"title":"Full name","description":"Display name.","type":"string"}}}

- name: wildcard-to-schema.json
  cmnd: bin/ysd -t jsc -C -
  stdi: |
    +Str: +Str
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","additionalProperties":{"type":"string"}}

- name: any-wildcard-to-schema.json
  cmnd: bin/ysd -t jsc -C -
  stdi: |
    +Str: +Any
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object"}

- name: wildcard-next-to-definition
  cmnd: bin/ysd -t jsc -C -
  stdi: |
    +label: +Str

    +Str: +label
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","additionalProperties":{"$ref":"#\/$defs\/label"},"$defs":{"label":{"type":"string"}}}

- name: nested-shaped-and-open-maps
  cmnd: bin/ysd -t jsc -C -
  stdi: |
    server:
      port: +Int
    data: +Map{+Any}
    labels:
      fixed?: +Str
      +Str:
        .type: +Str
        .size: 1-20
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","additionalProperties":false,"required":["server","data","labels"],"properties":{"server":{"type":"object","additionalProperties":false,"required":["port"],"properties":{"port":{"type":"integer"}}},"data":{"type":"object"},"labels":{"type":"object","additionalProperties":{"type":"string","minLength":1,"maxLength":20},"properties":{"fixed":{"type":"string"}}}}}

- name: reject-additional-properties-directive
  cmnd: |
    sh -c '
      output=$(printf "%s\n" "-additionalProperties: false" |
        bin/ysd -t jsc -C - 2>&1)
      status=$?
      test $status -eq 2
      printf "%s\n" "$output" | sed -n 1p
    '
  want: |
    ysd: unsupported yamlschema directive: -additionalProperties; use +Str

- name: reject-dash-directive
  cmnd: |
    sh -c '
      output=$(printf "%s\n" "field:" "  -base: +Str" |
        bin/ysd -t jsc -C - 2>&1)
      status=$?
      test $status -eq 2
      printf "%s\n" "$output" | sed -n 1p
    '
  want: |
    ysd: unsupported yamlschema directive: -base; use .type

- name: reject-uppercase-title-directive
  cmnd: |
    sh -c '
      output=$(printf "%s\n" ".Name: Old title" |
        bin/ysd -t jsc -C - 2>&1)
      status=$?
      test $status -eq 2
      printf "%s\n" "$output" | sed -n 1p
    '
  want: |
    ysd: unsupported yamlschema directive: .Name; use .title

- name: pretty-schema.json
  cmnd: bin/ysd -t jsc -
  stdi: |
    s: +Str
  want: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "additionalProperties": false,
      "required": [
        "s"
      ],
      "properties": {
        "s": {
          "type": "string"
        }
      }
    }

done:
