#!/usr/bin/env ys-0

use ys::taptest: :all

test::

- name: generated-comment
  cmnd: |
    sh -c '
      set -eu
      tmp=$(mktemp -d)
      trap "rm -r \"$tmp\"" EXIT
      printf "name: +Str\n" > "$tmp/contact.ysd.yaml"
      bin/ysd -t jsc -C "$tmp/contact.ysd.yaml" |
        perl -pe "s/YAMLSCHEMA v[0-9]+[.][0-9]+[.][0-9]+/YAMLSCHEMA vVERSION/"
    '
  want: |
    {"$comment":"DO NOT EDIT. THIS FILE GENERATED BY YAMLSCHEMA vVERSION","$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","properties":{"name":{"type":"string"}},"required":["name"],"additionalProperties":false}

- name: types-to-schema.json
  cmnd: bin/ysd -t schema.json -C -
  stdi: |
    s: +Str
    i: +Int
    n: +Num
    b: +Bool
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","properties":{"s":{"type":"string"},"i":{"type":"integer"},"n":{"type":"number"},"b":{"type":"boolean"}},"required":["s","i","n","b"],"additionalProperties":false}

- name: refs-and-regex-to-schema.json
  cmnd: bin/ysd -t schema.json -C -
  stdi: |
    +email: +Str =~"\S+@\S+"

    host: +Str
    admin?: +email
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","properties":{"host":{"type":"string"},"admin":{"$ref":"#\/$defs\/email"}},"required":["host"],"additionalProperties":false,"$defs":{"email":{"type":"string","pattern":"^\\S+@\\S+$"}}}

- name: match-find-and-regex-to-schema.json
  cmnd: bin/ysd -t schema.json -C -
  stdi: |
    full: =~"abc"
    alias: match:"xyz"
    found: find:"abc"
    short: /abc/
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","properties":{"full":{"type":"string","pattern":"^abc$"},"alias":{"type":"string","pattern":"^xyz$"},"found":{"type":"string","pattern":"abc"},"short":{"type":"string","pattern":"abc"}},"required":["full","alias","found","short"],"additionalProperties":false}

- name: defs-only-to-schema.json
  cmnd: bin/ysd -t schema.json -C -
  stdi: |
    +airflow: +Str [front-to-rear,rear-to-front]
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","$defs":{"airflow":{"type":"string","enum":["front-to-rear","rear-to-front"]}}}

- name: defs-only-roundtrip
  cmnd: sh -c 'bin/ysd -Rq - && echo OK'
  stdi: |
    {
      "$defs": {
        "airflow": {
          "type": "string",
          "enum": ["front-to-rear", "rear-to-front"]
        }
      }
    }
  want: |
    OK

- name: compact-enum-to-schema.json
  cmnd: bin/ysd -t schema.json -C -
  stdi: |
    role: +Str [admin,user,guest]
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","properties":{"role":{"type":"string","enum":["admin","user","guest"]}},"required":["role"],"additionalProperties":false}

- name: list-suffix-to-schema.json
  cmnd: bin/ysd -t schema.json -C -
  stdi: |
    tags: +Str[1+,!]
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","properties":{"tags":{"type":"array","items":{"type":"string"},"uniqueItems":true,"minItems":1}},"required":["tags"],"additionalProperties":false}

- name: any-list-omits-empty-items
  cmnd: bin/ysd -t schema.json -C -
  stdi: |
    anything: +Any[]
    strings: +Str[]
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","properties":{"anything":{"type":"array"},"strings":{"type":"array","items":{"type":"string"}}},"required":["anything","strings"],"additionalProperties":false}

- name: explicit-block-to-schema.json
  cmnd: bin/ysd -t schema.json -C -
  stdi: |
    port:
      .type: +Int
      .range: 1..65535
      .init: 8080
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","properties":{"port":{"type":"integer","default":8080,"minimum":1,"maximum":65535}},"required":["port"],"additionalProperties":false}

- name: numeric-range-shorthand-to-schema.json
  cmnd: bin/ysd -t schema.json -C -
  stdi: |
    port: 1..65535
    age: 0..
    debt: ..-1
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","properties":{"port":{"type":"integer","minimum":1,"maximum":65535},"age":{"type":"integer","minimum":0},"debt":{"type":"integer","maximum":-1}},"required":["port","age","debt"],"additionalProperties":false}

- name: annotations-to-schema.json
  cmnd: bin/ysd -t schema.json -C -
  stdi: |
    .ysid: https://example.com/arrays.ysd.yaml
    .title: Arrays
    .desc: Arrays of strings and objects
    name:
      .type: +Str
      .title: Full name
      .desc: Display name.
  want: |
    {"$id":"https:\/\/example.com\/arrays.schema.json","$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","title":"Arrays","description":"Arrays of strings and objects","type":"object","properties":{"name":{"title":"Full name","description":"Display name.","type":"string"}},"required":["name"],"additionalProperties":false}

- name: wildcard-to-schema.json
  cmnd: bin/ysd -t schema.json -C -
  stdi: |
    +Str: +Str
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","additionalProperties":{"type":"string"}}

- name: any-wildcard-to-schema.json
  cmnd: bin/ysd -t schema.json -C -
  stdi: |
    +Str: +Any
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object"}

- name: wildcard-next-to-definition
  cmnd: bin/ysd -t schema.json -C -
  stdi: |
    +label: +Str

    +Str: +label
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","additionalProperties":{"$ref":"#\/$defs\/label"},"$defs":{"label":{"type":"string"}}}

- name: nested-shaped-and-open-maps
  cmnd: bin/ysd -t schema.json -C -
  stdi: |
    server:
      port: +Int
    data: +Map{+Any}
    labels:
      fixed?: +Str
      +Str:
        .type: +Str
        .size: 1-20
  want: |
    {"$schema":"https:\/\/json-schema.org\/draft\/2020-12\/schema","type":"object","properties":{"server":{"type":"object","properties":{"port":{"type":"integer"}},"required":["port"],"additionalProperties":false},"data":{"type":"object"},"labels":{"type":"object","properties":{"fixed":{"type":"string"}},"additionalProperties":{"type":"string","minLength":1,"maxLength":20}}},"required":["server","data","labels"],"additionalProperties":false}

- name: reject-additional-properties-directive
  cmnd: |
    sh -c '
      output=$(printf "%s\n" "-additionalProperties: false" |
        bin/ysd -t schema.json -C - 2>&1)
      status=$?
      test $status -eq 2
      printf "%s\n" "$output" | sed -n 1p
    '
  want: |
    ysd: unsupported yamlschema directive: -additionalProperties; use +Str

- name: reject-dash-directive
  cmnd: |
    sh -c '
      output=$(printf "%s\n" "field:" "  -base: +Str" |
        bin/ysd -t schema.json -C - 2>&1)
      status=$?
      test $status -eq 2
      printf "%s\n" "$output" | sed -n 1p
    '
  want: |
    ysd: unsupported yamlschema directive: -base; use .type

- name: reject-uppercase-title-directive
  cmnd: |
    sh -c '
      output=$(printf "%s\n" ".Name: Old title" |
        bin/ysd -t schema.json -C - 2>&1)
      status=$?
      test $status -eq 2
      printf "%s\n" "$output" | sed -n 1p
    '
  want: |
    ysd: unsupported yamlschema directive: .Name; use .title

- name: pretty-schema.json
  cmnd: bin/ysd -t schema.json -
  stdi: |
    s: +Str
  want: |
    {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "type": "object",
      "properties": {
        "s": {
          "type": "string"
        }
      },
      "required": [
        "s"
      ],
      "additionalProperties": false
    }

done:
